refactor: update if condition in github action workflow

diff --git a/.github/workflows/docker-build-and-push-workflow.yml b/.github/workflows/docker-build-and-push-workflow.yml
--- a/.github/workflows/docker-build-and-push-workflow.yml
+++ b/.github/workflows/docker-build-and-push-workflow.yml
@@ -246,9 +246,10 @@ jobs:
 
         EXIT_CODE=$(docker inspect --format='{{json .State.ExitCode}}' soapui-testrunner)
         echo "Exit Code: $EXIT_CODE"
-        if [ "$EXIT_CODE" -ne 0 ]; then
-          echo "Test(s) failed. Failing the job."
-          exit 1
+        if [ "$EXIT_CODE" -ne 0 ]
+          then
+            echo "Test(s) failed. Failing the job."
+            exit 1
         fi
 
         docker-compose -f ./docker-compose.zaakbrug.dev.yml -f ./docker-compose.zaakbrug.postgres.yml -f ./docker-compose.openzaak.dev.yml down
