Gt 797 run automatically soap UI e2e tests in ci/cd pipeline (#208)
* feat: soapui profile added to docker-compose file

* feat: run-soapui-tests job added

* fix: directory update

* fix: dependency update for trial

* fix: take dependency update back

* fix: trial

* fix: take back the trial

* fix: timeout attribute added to test job

* fix: timeout attribute level updated

* fix: update versioning

* fix: status path update

* fix: typo

* fix: update docker-compose down command

* chore: .

* chore: .

* fix: update timeout

* chore: trial

* fix: docker-compose.postgres added in command

* fix: typo

* chore: typo

* chore: .

* chore: typo

* chore: trial

* chore: trial back

* fix: docker-compose down command updated

* fix:make url localhost from host.docker.internal

* fix: update url

* fix: update urls in test suite

* fix: double slash removed from url path

* fix: path updates in test cases

* fix: update COMMAND_LINE

* fix: remove double slash from url path

* fix: add -d to docker-compose command

* fix: update reports path

* fix: reports path updated

* fix: update status

* fix: update status

* fix: add 'failing the job' if tests are failed

* fix: add always run for uploading reports

* refactor: update if condition in github action workflow

* chore: fail the test on purpose for checking

* fix: move docker-compose down command above failing job

* chore: remove intentionally failing assertion

* feat: adding host-mode to be able to run in any environment

* test: fail the tests intentionally

* test: remove intentionally failing assertion

* chore: clean up

* chore: clean up dynamic property values in test cases

* chore: removed the test file to merge master into

* typo: removed extra colon

* chore: updating contributing file regarding to test automation.

* fix: double slash problem fixed

* trial: just to test, will be taken back

* chore: taking the trial back

* chore: removed extra element

* chore: test file removed to get the updated one from master

* fix: test suite name is not used in docker command to run all suites

* feat: new command line arguments added

* fix: wsdl file is defined in container as volume since tests were failing because of schema assertion

* test: trials to retrive some docker image inspect

* test: trial

* test: trial

* test: trial

* test:trial

* test: trial

* test: trial

* test: trial

* test: trial

* test: trial

* test: time difference condition has beeen added to be sure the tests have been run

* chore: update filing message

* chore: ineffective commit to trigger CI

* fix: the condition which is checking if there is any test report in the e2e/reports folder added

* test: check if the condition works

* chore: taking the commit verifying if the condition works back

* chore: run-till-healty job was removed since running soapui tests already verifies the same health check

* test: testing openzaak 1.10.3, this commit will be undone

* chore: undo the last commit

---------

Co-authored-by: Meric Akgul <meric@wearefrank.nl>
Co-authored-by: MLenterman <marcellenterman@hotmail.com>

diff --git a/.github/workflows/docker-build-and-push-workflow.yml b/.github/workflows/docker-build-and-push-workflow.yml
--- a/.github/workflows/docker-build-and-push-workflow.yml
+++ b/.github/workflows/docker-build-and-push-workflow.yml
@@ -153,10 +153,13 @@ jobs:
   #     with:
   #       sarif_file: 'trivy-results.sarif'
 
-  run-till-healthy:
+  run-soapui-tests:
     runs-on: ubuntu-latest
     needs: build
     steps:
+    - 
+      name: Checkout
+      uses: actions/checkout@v3
     -  
       name: "Download Docker tar"
       uses: actions/download-artifact@v2
@@ -168,37 +171,53 @@ jobs:
       run: |
         docker load --input /tmp/docker.tar
         docker image ls -a
-    - 
-      name: Test Docker image
+    -
+      name: "Run SoapUI Tests"
       run: |
-        set -x
         if [ ${{ inputs.latest-tag }} == true ]
           then
-            docker image inspect ${{ inputs.docker-image-repo }}:latest
-            docker run --rm -p 8080:8080 -e dtap.stage=LOC --name=test -d ${{ inputs.docker-image-repo }}:latest
+            export ZAAKBRUG_VERSION="latest"
           else
-            docker image inspect ${{ needs.build.outputs.docker-meta-tags }}
-            docker run --rm -p 8080:8080 -e dtap.stage=LOC --name=test -d ${{ needs.build.outputs.docker-meta-tags }}
+            export ZAAKBRUG_VERSION="${{ needs.build.outputs.docker-meta-tags }}"
+            export ZAAKBRUG_VERSION="${ZAAKBRUG_VERSION##*:}"
         fi
+        docker image inspect ${{ inputs.docker-image-repo }}:${ZAAKBRUG_VERSION}
+        docker-compose -f ./docker-compose.zaakbrug.dev.yml -f ./docker-compose.zaakbrug.postgres.yml -f ./docker-compose.openzaak.dev.yml --profile soapui up -d
+        docker ps
 
-        sleep 30
+        sleep 90
 
-        RETRY_COUNT=0
-        HEALTH=$(docker inspect --format='{{json .State.Health.Status}}' test)
-        until [ "$HEALTH" = '"healthy"' ]
+        STATUS=$(docker inspect --format='{{json .State.Status}}' soapui-testrunner)
+        until [ "$STATUS" = '"exited"' ]
         do
-          if [ $RETRY_COUNT -gt 15 ]
-            then
-                docker inspect test
-                docker logs test
-                exit 1
-          fi
-
-          let RETRY_COUNT+=1
-          HEALTH=$(docker inspect --format='{{json .State.Health.Status}}' test)
+          STATUS=$(docker inspect --format='{{json .State.Status}}' soapui-testrunner)
           sleep 15
         done
 
-        docker inspect test
-        docker logs test
-      timeout-minutes: 5
+        EXIT_CODE=$(docker inspect --format='{{json .State.ExitCode}}' soapui-testrunner)
+        echo "Exit Code: $EXIT_CODE"
+
+        docker-compose -f ./docker-compose.zaakbrug.dev.yml -f ./docker-compose.zaakbrug.postgres.yml -f ./docker-compose.openzaak.dev.yml down
+        
+        if [ "$EXIT_CODE" -ne 0 ]
+          then
+            echo "Test(s) failed. Failing the job."
+            exit 1
+        fi
+
+      timeout-minutes: 30
+    -
+      name: Check if test reports created
+      run: |
+        if [ -z "$(ls -A e2e/reports)" ]
+          then
+            echo "There is no test report found, tests might not have been run. Failing the job."
+            exit 1
+        fi
+    - 
+      name: "Upload Sarif report as artifact"
+      if: always()
+      uses: actions/upload-artifact@v2
+      with:
+        name: test-results
+        path: e2e/reports
