sdf

diff --git a/.github/workflows/sync-from-template-repo.yml b/.github/workflows/sync-from-template-repo.yml
--- a/.github/workflows/sync-from-template-repo.yml
+++ b/.github/workflows/sync-from-template-repo.yml
@@ -19,10 +19,44 @@ jobs:
         with:
           token: ${{secrets.token}}
 
-      - name: actions-template-sync
-        uses: AndreasAugustin/actions-template-sync@v2
+      - uses: actions/setup-python@v4
         with:
-          github_token: ${{secrets.token}}
-          source_repo_path: wearefrank/skeleton
-          is_dry_run: false
-          upstream_branch: main
+          python-version: '3.10'
+  
+      - name: Install Cruft
+        run: pip3 install cruft
+
+      - name: Check if update is available
+        continue-on-error: false
+        id: check
+        run: |
+          CHANGES=0
+          if [ -f .cruft.json ]; then
+            if ! cruft check; then
+              CHANGES=1
+            fi
+          else
+            echo "Missing .cruft.json"
+          fi
+
+          echo "has_changes=$CHANGES" >> "$GITHUB_OUTPUT"
+
+      - name: Run update if available
+        if: steps.check.outputs.has_changes == '1'
+        run: |
+          git config user.name "$GITHUB_ACTOR"
+          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+
+          cruft update --skip-apply-ask --refresh-private-variables
+          git restore --staged .
+
+      - name: Create pull request
+        if: steps.check.outputs.has_changes == '1'
+        uses: peter-evans/create-pull-request@v4
+        with:
+          token: ${{secrets.token}}
+          commit-message: 'build(dependencies): project template sync'
+          branch: template-sync
+          delete-branch: true
+          branch-suffix: timestamp
+          title: 'build(dependencies): project template sync'
